name: Deploy Laravel

on:
  push:
    branches:
      - develop
      - master

jobs:
  deploy_dev:
    if: github.ref == 'refs/heads/develop'
    runs-on: [self-hosted, deploy_dev]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          clean: false

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: ctype, curl, xml, fileinfo, mbstring, openssl, pdo, mysql, zip, bcmath, grpc

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: |
          composer install --no-interaction

      - name: Configure Environment Variables
        run: |
          php artisan config:cache
          php artisan route:cache

      - name: Run Database Migrations
        run: |
          php artisan migrate

      - name: Run frontend
        run: |
          npm run build

  deploy_prod:
    if: github.ref == 'refs/heads/master'
    runs-on: [self-hosted, deploy_pro]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          clean: false

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: ctype, curl, xml, fileinfo, mbstring, openssl, pdo, mysql, zip, bcmath, grpc

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: |
          composer install --no-interaction --no-dev --optimize-autoloader

      - name: Configure Environment Variables
        run: |
          php artisan config:cache
          php artisan route:cache

      - name: Run Database Migrations
        run: |
          php artisan migrate

      - name: Run frontend
        run: |
          npm run build
